sudo: false
language: python
python: '3.5'
env:
  matrix:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  global:
    secure: UfxqhkzlkctWdPsnPOr1z/MM3+VM1DYpYQcCScO5sXelxBQVDCzHWEF3tAar3FIVn06yo+trIRYowJGRuK5G+ypkRQvqn5RNkom1iSOArdWIvkJDiFoA6b2s3C9fWjobSLi4j2wg4ozwaiaxkQB6LMViPdM0lCkAUqu7ON8QqJG1oKYcaBPWp7bPkN4Tq1UgMnSyBo1Dgo47qMf/rFDbZ014uOOuq4M2u1gTjcVFpH2J9p8qmyuD6sUH3OoYT64bFxnsYzM1jH0S+K1AdoPliOyCJIE3YtYsvjLTjDJnvkWun6hHxa5G8suyLi7TswmdQC6XNErcOP7gXqhYx0+/glAKevBLpK+rv/+3n4AlNYTnFIY3MQi6mn//GhFAIDRW6VN2L3XGZx9auz7GR7ty3uX3v0RsEho2//N2syniu2untx88KBvdp0MpN9dSJKG6TGH3M2DTZ5Hy80wbQtqeKkvlFU28/hwtJq4hcuJP0QPGbpDsG5XafNTyO/kzAa8nAxgwu1VPmLy0r5IuiqvacRRV/rLG4TrY9BTietuMUXZMaHn9OoM5WHMlXNrn3zh2dQ+a5RXPdz1DG9nX0nlCFV3W4kxu65Bx5veldATurvuWnIweoqFSQRuFs9J/HjZpkmud7M7e36uI9XyOt1TIF9++q07lus6dYTHp1Rbclx0=
install:
- pip install tox
script:
- git clean -f -d -x
- tox
matrix:
  fast_finish: true
deploy:
  provider: pypi
  user: mkdocsdeploy
  distributions: sdist bdist_wheel
  password:
    secure: 0HsKViPmpI13uG1wEeIQ6fRvdX4x1XZNufzQgMyhEDKj0Shuw5q7xt+KAuAULBpNbOZj1XzgdCmWxC6fZq2K5/Lm3aHZc2ZXDEhfVkIC8kCGCbPE/Ziq82CA2iyOWSdkLRdssaYebKeZy0qi41Y8Xxag7xGHo/atoUPL5Aegp6KBDJ6Q4160zyAmegy3XFR47m/43fyH5CoUlJf72Qf5/mhIVE0HqG/pYs8jpXX4I0ICJLmlx8UQNdAu2ikd1316XwTdl+VwRzZTfUpJtaN0vldGJ5cQKFU7Iil7jiPUuB5WVzZqYC87Y9/9XCwhwXAWQCt+AjDrhaFEaU0koDgUreIUE3xOBu7NeUqRZuR9aGbQgLvTcoLL6NcWVEJi9qtOynWPgVCjNUU/RyiNTXtPwGBjaeU5ZN7cUukLjaKwCNxglyj/kOo2AwlK9x54FdxCfCs07hjmoBHhQyHSTk+Lk/w6xAxI7pWOvM+oacUQaToWgq6FBnua5VfYVe92MECNCDB6Ua2DRsW3QZtLnQz6MQaJCBv3nIVw1QhQUWwHohfxidgq8F5wleEf2Bd+vTKXGFD0uTDzP6NKuc26cbm3nIJt5u8hCd/Sdc+gf+fP3N7fIgG0grmt6bbb8u5MiOBvKwfQjgFiN9Xt3KGwWQowpOfUfYOD23sWX0nxnaLaAJA=
  on:
    tags: true
    repo: mkdocs/mkdocs-bootswatch
    condition: "$TOXENV = py35"
after_success:
- git remote add gh-token "https://${GH_TOKEN}@github.com:mkdocs/mkdocs-bootswatch.git";
- pip install mkdocs -U;
- if [[ $TOXENV == "py35" ]]; then mkdocs gh-deploy --clean --remote-name gh-token; fi;
